# Generated by Django 4.2.2 on 2023-06-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_candidate_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(default='', max_length=500),
        ),
    ]
